query EventTablesList(
  $eventId: ID!
  $pagination: PaginationInput
  $sort: [SortInput!]
  $filters: EventTableFilterInput
) {
  eventTablesList(eventId: $eventId, pagination: $pagination, sort: $sort, filters: $filters) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      totalCount
      pageSize
      page
      totalPagesCount
    }
    rows {
      id
      assignedGuests {
        id
        name
        email
      }
      capacity
      label
      name
      tableNumber
    }
  }
}
