query EventGuestList(
  $eventId: ID!
  $filters: EventGuestFilterInput
  $pagination: PaginationInput
  $sort: [SortInput!]
) {
  eventGuestList(eventId: $eventId, filters: $filters, pagination: $pagination, sort: $sort) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      totalCount
      pageSize
      page
      totalPagesCount
    }
    rows {
      email
      id
      gender
      eventId
      name
      phoneNumber
      status
      parentGuestId
      companions {
        id
        name
        email
      }
      countryCode
      formattedPhoneNumber
      numberOfCompanions
      invitationSent
      checkedIn
      qrCode {
        id
        name
        publicUrl
      }
      abayaLabelId
      abayaLabel {
        id
      }
      code
      seatId
      seatNumber
      tableNumber
      updatedAt
      updatedBy
      createdAt
    }
  }
}
