query EventHallList($eventId: ID!) {
  eventHallList(eventId: $eventId) {
    id
    eventId
    layoutVersion
    name
    status
    tableTemplates {
      capacity
      id
      numberOfTables
      seatNaming
      tableNaming
      tableShape
      createdObjectCount
    }
    updatedAt
    updatedBy
    createdBy
    createdAt
    boundary {
      radius
      shape
      width
      widthMeters
      heightMeters
      x
      y
      points {
        x
        y
      }
      height
    }
    coordinateSystem {
      height
      width
    }
  }
}
